import Head from "next/head";
import { useState } from "react";
import me from "../public/me.jpg";
import Image from "next/image";
import About from "../components/About";
import Main from "../components/Main";
import Skills from "../components/Skiils";
import Nav  from "../components/Nav";
import Projects from '../components/Projects'
// import Link from 'next/link'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const activeDarkMode = () =>{
   setDarkMode(!darkMode)
  }
  // const skills = [css3, github, html5, js, mysql, node, sass];
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Benjamin Makonen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* <section className="min-h-[90vh]"> */}
          <Nav activeDarkMode={activeDarkMode}/>
          <Main me={me} />
        {/* </section> */}
        {/* <section> */}
          <About me={me} />
          <Skills />
        {/* </section> */}
        {/* <section className="py-10"> */}
          <div>
            {/* <Link href='/test'> */}
            <h3 className="text-3xl py-1 dark:text-white ">My Project</h3>
            {/* </Link> */}
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <Projects/>
          {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg "
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={youTube}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className=""
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={spotifyApp}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div> */}
        {/* </section> */}
      </main>
    </div>
  );
}
