import Head from "next/head";
import { useState } from "react";
import me from "../public/me.jpg";
import Image from "next/image";
import About from "../components/About";
import Main from "../components/Main";
import Skills from "../components/Skiils";
import Nav  from "../components/Nav";
import Projects from '../components/Projects'
// import Link from 'next/link'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const activeDarkMode = () =>{
   setDarkMode(!darkMode)
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Benjamin Makonen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
          <Nav activeDarkMode={activeDarkMode} darkMode={darkMode}/>
          <Main me={me} />
          <About me={me} />
          <Skills />
          <Projects/>
      </main>
    </div>
  );
}
